M48
; DRILL file KiCad 10.0.5 date 2026-08-19T19:39:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-19T19:39:03+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X161.86Y-82.395
X167.64Y-82.395
T2
X162.185Y-59.392
X167.265Y-58.376
X167.265Y-60.408
M30
